variable "name_prefix" {}
variable "tags" {}
variable "environment" {}
variable "host_instance_count" {}
variable "host_instance_type" {}
variable "model_artifact_file_name" {}
variable "model_artifact_source_bucket" {}
variable "model_artifact_source_bucket_region" {}
variable "sagemaker_ecr" {}
variable "sagemaker_ecr_image_name" {}
variable "sagemaker_ecr_image_tag" {}
